spring.application.name: menu-service

server.port: 8083

security:
  basic:
    enabled: false

spring.oauth2:
  resource:
    jwt.keyUri: ${targets.uaa}/token_key

spring.jpa.hibernate.ddl-auto: update

menuBootstrap:
  items:
    - name: Full Rack of Ribs
      price: 20
    - name: 1/2 Rack
      price: 12