server.port: 8086

security:
  basic:
    enabled: false
    
zuul:
  routes:
    uaa:
      path: /uaa/**
      url: http://localhost:8080/uaa/
    menu:
      path: /menu/**
      url: http://localhost:8083/menuItems/
    myorders:
      path: /myorders/**
      url: http://localhost:8085/myorders/