server.port: 8084

security:
  basic:
    enabled: false
    
spring.oauth2:
  client:
    accessTokenUri: http://localhost:8080/uaa/oauth/token
    userAuthorizationUri: http://localhost:8080/uaa/oauth/authorize
    clientId: admin-portal
    clientSecret: secret
    scope: openid,menu.read,menu.write,order.admin
  resource:
    jwt.keyUri: http://localhost:8080/uaa/token_key

